name: Benchmarks

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  test:
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
        rust-version: ['1.64.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up matplotlib
        run: |
          pip install matplotlib

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run benchmarks
        run: |
          chmod +x run.sh
          ./run.sh
      
      - name: deploy gh-page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: page
